import { IBuilding } from 'shared/models/IBuilding';
import { IResponse } from 'shared/models/IResponse';

export const data: IBuilding[] = [
  {
    address: 'Новокосинская улица, 32, Москва, 111672',
    events: [
      {
        eventName: 'Сильная течь в системе отопления',
        chance: 50,
        date: '12.06',
      },
      { eventName: 'P1 <= 0', chance: 90, date: '12.06' },
    ],
    socialType: 'mkd',
    coords: [55.717482785, 37.828189394],
    coolingRate: 3,
    consumersCount: null,
    priority: 1,
    district: 'муниципальный округ Преображенское',
    networkType: null,
    characteristics: {
      'Год постройки': 1967,
      'Материал стен': 'Кирпич',
      Этажность: 8,
      'Кол-во квартир': 200,
      'Теплопроводность стен': 'Низкая',
      'Износ объекта по БТИ': 'Высокий',
      'Класс энергоэфективности': 'Высокий',
      'Признак аварийности здания': 'Признак',
    },
    connectionInfo: null,
  },
  {
    address: 'Новокосинская улица, 32, Москва, 111673',
    events: [
      {
        eventName: 'Сильная течь в системе отопления',
        chance: 50,
        date: '12.06',
      },
      { eventName: 'P1 <= 0', chance: 20, date: '12.06' },
    ],
    socialType: 'medicine',
    coords: [55.803579031, 37.513482336],
    coolingRate: 5,
    consumersCount: null,
    priority: 6,
    district: 'Восточное Измайлово',
    networkType: 'itp',
    characteristics: {
      'Год постройки': 1967,
      'Материал стен': 'Кирпич',
      Этажность: 8,
      'Кол-во квартир': 200,
      'Теплопроводность стен': 'Низкая',
      'Износ объекта по БТИ': 'Высокий',
      'Класс энергоэфективности': 'Высокий',
      'Признак аварийности здания': 'Признак',
    },
    connectionInfo: null,
  },
  {
    address: 'Новокосинская улица, 32, Москва, 123',
    events: [
      {
        eventName: 'Сильная течь в системе отопления',
        chance: 50,
        date: '12.06',
      },
      { eventName: 'P1 <= 0', chance: 20, date: '12.06' },
    ],
    socialType: 'medicine',
    coords: [55.720046086, 37.797663794],
    coolingRate: 5,
    consumersCount: null,
    priority: 3,
    district: 'муниципальный округ Преображенское',
    networkType: null,
    characteristics: {
      'Год постройки': 1967,
      'Материал стен': 'Кирпич',
      Этажность: 8,
      'Кол-во квартир': 200,
      'Теплопроводность стен': 'Низкая',
      'Износ объекта по БТИ': 'Высокий',
      'Класс энергоэфективности': 'Высокий',
      'Признак аварийности здания': 'Признак',
    },
    connectionInfo: null,
  },
  {
    address: 'Новокосинская улица, 32, Москва, 1223',
    events: [
      {
        eventName: 'Сильная течь в системе отопления',
        chance: 50,
        date: '12.06',
      },
      { eventName: 'P1 <= 0', chance: 20, date: '12.06' },
    ],
    socialType: 'tp',
    coords: [55.766228272, 37.668013072],
    coolingRate: 5,
    consumersCount: null,
    priority: 4,
    district: 'муниципальный округ Преображенское',
    networkType: 'ctp',
    characteristics: {
      'Год постройки': 1967,
      'Материал стен': 'Кирпич',
      Этажность: 8,
      'Кол-во квартир': 200,
      'Теплопроводность стен': 'Низкая',
      'Износ объекта по БТИ': 'Высокий',
      'Класс энергоэфективности': 'Высокий',
      'Признак аварийности здания': 'Признак',
    },
    connectionInfo: null,
  },
  {
    address: 'Новокоси2нская улица, 32, Москва, 1223',
    events: [
      {
        eventName: 'Сильная течь в системе отопления',
        chance: 50,
        date: '12.06',
      },
      { eventName: 'P1 <= 0', chance: 20, date: '12.06' },
    ],
    socialType: 'education',
    coords: [55.815345188, 37.514882646],
    coolingRate: 5,
    consumersCount: null,
    priority: 5,
    district: 'Восточное Измайлово',
    networkType: null,
    characteristics: {
      'Год постройки': 1967,
      'Материал стен': 'Кирпич',
      Этажность: 8,
      'Кол-во квартир': 200,
      'Теплопроводность стен': 'Низкая',
      'Износ объекта по БТИ': 'Высокий',
      'Класс энергоэфективности': 'Высокий',
      'Признак аварийности здания': 'Признак',
    },
    connectionInfo: null,
  },
];

export const responseData: IResponse = {
  date: '15.10.2024',
  obj: [
    {
      id: 1,
      date: '15.10.2024',
      address: '1Новокосинская улица, 32, Москва, 111672',
      socialType: 'mkd',
      consumersCount: null,
      coords: [55.717482785, 37.828189394],
      event: 'Прорыв трубы',
      priority: 1,
      isLast: false,
      fullCooldown: 3,
      normCooldown: 2,
      district: 'Восточное Измайлово',
      characteristics: {
        'Год постройки': 1967,
        'Материал стен': 'Кирпич',
        Этажность: 8,
        'Кол-во квартир': 200,
        'Теплопроводность стен': 'Низкая',
        'Износ объекта по БТИ': 'Высокий',
        'Класс энергоэфективности': 'Высокий',
        'Признак аварийности здания': 'Признак',
      },
      connectionInfo: null,
    },
    {
      id: 2,
      date: '15.10.2024',
      address: '2Новокосинская улица, 32, Москва, 111672',
      socialType: 'education',
      consumersCount: null,
      coords: [55.720046086, 37.797663794],
      event: 'Прорыв трубы',
      priority: 2,
      isLast: false,
      fullCooldown: 3,
      normCooldown: 2,
      district: 'муниципальный округ Преображенское',
      characteristics: {
        'Год постройки': 1967,
        'Материал стен': 'Кирпич',
        Этажность: 8,
        'Кол-во квартир': 200,
        'Теплопроводность стен': 'Низкая',
        'Износ объекта по БТИ': 'Высокий',
        'Класс энергоэфективности': 'Высокий',
        'Признак аварийности здания': 'Признак',
      },
      connectionInfo: null,
    },
    {
      id: 3,
      date: '15.10.2024',
      address: 'Снайперская ул., д.11, стр.2',
      socialType: 'tp',
      consumersCount: 190,
      coords: [55.815345188, 37.514882646],
      event: 'Прорыв трубы',
      priority: 3,
      isLast: true,
      fullCooldown: 3,
      normCooldown: 2,
      district: 'муниципальный округ Преображенское',
      characteristics: {
        'Год постройки': 1967,
        'Материал стен': 'Кирпич',
        Этажность: 8,
        'Кол-во квартир': 200,
        'Теплопроводность стен': 'Низкая',
        'Износ объекта по БТИ': 'Высокий',
        'Класс энергоэфективности': 'Высокий',
        'Признак аварийности здания': 'Признак',
      },
      connectionInfo: null,
    },
  ],
};
