services:
  nginx:
    image: nginx:1.24.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/../etc/letsencrypt/live/adera-team.ru-0002/fullchain.pem:/etc/nginx/ssl/fullchain.pem        
      - ~/../etc/letsencrypt/live/adera-team.ru-0002/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
            - "80:80"
            - "443:443"
