services:
  minio:
    image: 'bitnami/minio:2024.5.28'
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file:
      - .env
    volumes:
######ВАЖНО: чтобы работы S3 был корректной необходимо дать пользователю 1001
######доступ к директории minio на каталог выше которая появится при первом неудачном пуске контейнера
###### BASH: sudo chown 1001 ../minio
      - ../minio/minio-data:/data
