services:
  minio:
    image: 'bitnami/minio:2024.5.28'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-adera-user
      - MINIO_ROOT_PASSWORD=minio-adera-password
      - MINIO_DATA_DIR=/data
#      - MINIO_SERVER_URL=https://minio.adera-team.ru
      - MINIO_PROTOCOL=https
    volumes:
      - ./minio/minio-data:/data
