version: "3"

services:
    pgadmin:
      image: dpage/pgadmin4
      restart: on-failure
      ports:
        - '5050:80'
      env_file:
        - .env
      networks:
        - backend_network
networks:
  backend_network:
    external: true


