version: "3"

services:
    pgadmin:
      image: dpage/pgadmin4
      restart: on-failure
      ports:
        - '5050:80'
      environment:
        - PGADMIN_DEFAULT_EMAIL=post@gres.com
        - PGADMIN_DEFAULT_PASSWORD=postgres
      networks:
        - sql_network
networks:
  sql_network:
    external: true


