version: "3"

services:
    pgadmin:
      image: dpage/pgadmin4
      restart: on-failure
      ports:
        - '5050:80'
      environment:
        - PGADMIN_DEFAULT_EMAIL=postgres@admin.com
        - PGADMIN_DEFAULT_PASSWORD=postgres
#        - PGADMIN_DISABLE_POSTFIX=true
      networks:
        - backend_network
networks:
  backend_network:
    external: true


