version: "3.3"
services:
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: "always"
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - network
      - fastapi-celery_network
    volumes:
      - ./../../../postgres/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  nest:
    depends_on:
      - postgres
    image: node:20
    environment:
      DATABASE_HOST: postgres
    restart: "always"
    volumes:
      - ../../:/nest-app/
    ports:
      - 8000:8000
    networks:
      - network
      - fastapi-celery_network
    working_dir: /nest-app/
    entrypoint: bash -c "npm run create-entities-index && npx nx serve backend --skip-nx-cache"
    links:
      - "postgres:postgres"
networks:
  network:
    driver: bridge
  fastapi-celery_network:
    external: true

